[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "clustering-pipeline"
version = "0.1.0"
description = "A clustering pipeline"
dependencies = [
    "pandas",
    "scikit-learn",
    "numpy",
    "pydantic",
    "click",
    "tqdm",
    "joblib",
    "pyyaml",
]

[tool.setuptools.packages.find]
include = ["clustering_pipeline*"]